name: Keep Backend Alive

on:
  schedule:
    - cron: '*/28 * * * *'        # At minute 0, 28
    - cron: '14-59/28 * * * *'    # At minute 14, 42
  workflow_dispatch:         # Manual trigger support

# If a new run is triggered while the old one is still running,
# cancel the old one and start the new.
concurrency:
  group: keep-backend-alive
  cancel-in-progress: true

jobs:
  ping-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run keep-alive script
        run: python main.py
